-- Deploy swipe-swap/schema:warehouse/individual to pg
-- requires: warehouse/schema

begin;

set local search_path to warehouse;

create table individual (
    individual_id integer primary key generated by default as identity,
    username text not null unique,
    first_name text not null,
    last_name text not null,
    created timestamp with time zone not null default now(),

    -- TODO: consider verified/unverified column
    -- TODO: consider adding gender
    -- TODO: consider adding location
    -- TODO: consider adding age

    details jsonb
);

comment on table individual is 'An individual entity';
comment on column individual.individual_id is 'Internal id of this individual';
comment on column individual.username is 'External-facing identifier for this individual';
comment on column individual.first_name is 'External-facing first name (given name) of this individual';
comment on column individual.last_name is 'Last-name (given name) of this individual';
comment on column individual.created is 'When the individual entity was created';
comment on column individual.details is 'Additional information about this individual which does not have a place in this relational schema';

create index individual_username_idx on individual (username);
create index individual_details_idx on individual using gin (details jsonb_path_ops);
commit;
